#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
一键更新脚本 - 读取config.json并立即生成所有静态文件
使用方法：python update-files.py
"""

import json
import os
import sys
from datetime import datetime

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    config_file = os.path.join(base_dir, 'config.json')
    
    print("=" * 60)
    print("🔄 一键更新静态文件")
    print("=" * 60)
    print(f"⏰ 时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    if not os.path.exists(config_file):
        print(f"❌ 错误：找不到配置文件 {config_file}")
        return False
    
    try:
        with open(config_file, 'r', encoding='utf-8') as f:
            config = json.load(f)
        
        domain = config.get('siteDomain', 'your-domain.github.io')
        protocol = config.get('settings', {}).get('protocol', 'https')
        
        if not domain.startswith(('http://', 'https://')):
            base_url = f"{protocol}://{domain}"
        else:
            base_url = domain
        
        print(f"\n📝 配置信息:")
        print(f"   域名: {domain}")
        print(f"   协议: {protocol}")
        print(f"   完整URL: {base_url}")
        
        # ========== 1. 生成 sitemap.xml ==========
        print(f"\n🗺️ [1/3] 生成 sitemap.xml...")
        
        sitemap_path = os.path.join(base_dir, 'sitemap.xml')
        sitemap_content = f'''<?xml version='1.0' encoding='utf-8'?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{base_url}/</loc>
    <lastmod>{datetime.now().strftime('%Y-%m-%d')}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>{base_url}/index.html</loc>
    <lastmod>{datetime.now().strftime('%Y-%m-%d')}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>'''
        
        with open(sitemap_path, 'w', encoding='utf-8') as f:
            f.write(sitemap_content)
        
        sitemap_size = os.path.getsize(sitemap_path)
        print(f"   ✅ sitemap.xml 已生成 ({sitemap_size} bytes)")
        print(f"   📍 {base_url}/")
        print(f"   📍 {base_url}/index.html")
        
        # ========== 2. 生成 robots.txt ==========
        print(f"\n🤖 [2/3] 生成 robots.txt...")
        
        robots_path = os.path.join(base_dir, 'robots.txt')
        robots_content = f"""# Robots.txt for {base_url}
# Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# Auto-generated by Content Collector System

User-agent: *
Allow: /
Allow: /index.html
Allow: /sitemap.xml

Disallow: /*.json$
Disallow: /*.py$
Disallow: /*.sh$
Disallow: /*.yml$
Disallow: /*.yaml$
Disallow: /config*
Disallow: /data*
Disallow: /collector*
Disallow: /.github/

Sitemap: {base_url}/sitemap.xml

Crawl-delay: 1"""
        
        with open(robots_path, 'w', encoding='utf-8') as f:
            f.write(robots_content)
        
        robots_size = os.path.getsize(robots_path)
        print(f"   ✅ robots.txt 已生成 ({robots_size} bytes)")
        print(f"   🔗 Sitemap: {base_url}/sitemap.xml")
        
        # ========== 3. 更新 data.json ==========
        print(f"\n📄 [3/3] 更新 data.json...")
        
        data_path = os.path.join(base_dir, 'data.json')
        
        if os.path.exists(data_path):
            with open(data_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            old_domain = data.get('siteDomain', '')
            data['siteDomain'] = base_url
            
            ad_config = config.get('ad', {})
            data['ad'] = ad_config
            
            sources = config.get('sources', [])
            source_names_configured = [s['name'] for s in sources]
            existing_sources = data.get('sources', {})
            
            removed_count = 0
            for source_name in list(existing_sources.keys()):
                if source_name not in source_names_configured:
                    del existing_sources[source_name]
                    removed_count += 1
            
            data['sourceNames'] = list(existing_sources.keys())
            data['stats'] = {
                'totalSources': len(existing_sources),
                'totalItems': sum(len(items) for items in existing_sources.values()),
                'sourceStats': {name: len(items) for name, items in existing_sources.items()}
            }
            
            with open(data_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            
            data_size = os.path.getsize(data_path)
            print(f"   ✅ data.json 已更新 ({data_size} bytes)")
            
            if old_domain and old_domain != base_url:
                print(f"   🌐 域名已变更: {old_domain} → {base_url}")
            if removed_count > 0:
                print(f"   🗑️ 清理了 {removed_count} 个无效数据源")
        else:
            print(f"   ⚠️  data.json 不存在，跳过")
        
        # ========== 完成 ==========
        print("\n" + "=" * 60)
        print("✅ 所有静态文件已成功生成！")
        print("=" * 60)
        print(f"\n生成的文件:")
        print(f"  📄 sitemap.xml  ({os.path.getsize(sitemap_path)} bytes)")
        print(f"  🤖 robots.txt   ({os.path.getsize(robots_path)} bytes)")
        if os.path.exists(data_path):
            print(f"  📊 data.json    ({os.path.getsize(data_path)} bytes)")
        
        print(f"\n💡 提示：现在可以提交代码并推送到GitHub")
        print(f"   git add . && git commit -m '更新静态文件' && git push")
        
        return True
        
    except Exception as e:
        print(f"\n❌ 错误: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)